services:
  nav:
    image: starwisher/starnav
    container_name: starnav
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./src/config:/app/src/config
    environment:
      - ADMIN_USERNAME=admin # 管理员用户名
      - ADMIN_PASSWORD=admin123 # 管理员密码
      # - CORS_ORIGINS=https://your-domain.com # 生产环境设置允许的域名
    restart: always
