services:
  nav:
    image: starwisher/starnav
    container_name: starnav
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/config/data.json:/app/src/config/data.json
    environment:
      - ADMIN_USERNAME=admin # 管理员用户名
      - ADMIN_PASSWORD=admin123 # 管理员密码
      - JWT_SECRET=random_secret_string # JWT 签名密钥，长度至少 32 位
    restart: always
