services:
  nav:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src/config/data.json:/app/src/config/data.json
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - JWT_SECRET=starnav_secret_key_2025
    restart: always
