services:
  nav:
    image: starwisher/starnav:latest
    container_name: starnav
    ports:
      - "3333:3333"
    volumes:
      - ./src/config:/app/src/config
    environment:
      - ADMIN_USERNAME=admin # 管理员用户名
      - ADMIN_PASSWORD=admin123 # 管理员密码
      - JWT_SECRET=random_secret_string # JWT 签名密钥，长度至少 32 位
    restart: always
